# Generated by Django 6.0.2 on 2026-03-04 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade_aprovacao', models.FloatField()),
                ('probabilidade_media_acerto', models.FloatField()),
                ('rating_usuario', models.FloatField()),
                ('rating_concurso', models.FloatField()),
                ('ultima_resolucao_processada', models.DateTimeField()),
                ('data_calculo', models.DateTimeField(auto_now=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.concurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'concurso')},
            },
        ),
        migrations.CreateModel(
            name='PrevisaoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade_aprovacao', models.FloatField()),
                ('probabilidade_media_acerto', models.FloatField()),
                ('rating_usuario', models.FloatField()),
                ('rating_materia', models.FloatField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia')),
                ('previsao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='analytics.previsaoaprovacao')),
            ],
            options={
                'unique_together': {('previsao', 'materia')},
            },
        ),
    ]
