# Generated by Django 6.0.2 on 2026-03-06 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_remove_materia_concurso'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaFundamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.FloatField(default=1)),
                ('repeticoes', models.IntegerField(default=0)),
                ('facilidade', models.FloatField(default=2.5)),
                ('proxima_revisao', models.DateTimeField()),
                ('ultima_resposta', models.DateTimeField(auto_now=True)),
                ('fundamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.fundamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fundamento')},
            },
        ),
    ]
