# Generated by Django 6.0.2 on 2026-03-06 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidadeusuariofundamento',
            name='acertou',
        ),
        migrations.RemoveField(
            model_name='habilidadeusuariofundamento',
            name='data_resolucao',
        ),
        migrations.RemoveField(
            model_name='habilidadeusuariofundamento',
            name='modo',
        ),
        migrations.RemoveField(
            model_name='habilidadeusuariofundamento',
            name='opcao_escolhida',
        ),
        migrations.RemoveField(
            model_name='habilidadeusuariofundamento',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='habilidadeusuariofundamento',
            name='tempo_em_segundos',
        ),
        migrations.AlterField(
            model_name='habilidadeusuariofundamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
