# Generated by Django 6.0.2 on 2026-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_habilidadeusuariofundamento_acertou_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidadeusuariofundamento',
            name='consistencia',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='habilidadeusuariofundamento',
            name='habilidade',
            field=models.FloatField(default=900),
        ),
    ]
