# Generated by Django 6.0.2 on 2026-03-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('banca', models.CharField(max_length=150)),
                ('ano', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fundamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('peso_relevancia', models.FloatField(default=1.0, help_text='Impacto do fundamento na dificuldade real')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='questoes/')),
                ('origem', models.CharField(db_index=True, max_length=150)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('nivel_sugerido', models.IntegerField()),
                ('nivel_dinamico', models.FloatField(blank=True, null=True)),
                ('total_respostas', models.PositiveIntegerField(default=0)),
                ('total_acertos', models.PositiveIntegerField(default=0)),
                ('indice_discriminacao', models.FloatField(default=0)),
                ('resolucao_mestra', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('concurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='academico.concurso')),
                ('fundamentos', models.ManyToManyField(related_name='questoes', to='academico.fundamento')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='academico.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='academico.materia')),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='academico.topico'),
        ),
        migrations.AddField(
            model_name='fundamento',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentos', to='academico.topico'),
        ),
    ]
