# Generated by Django 6.0.2 on 2026-03-04 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='concurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academico.concurso'),
        ),
    ]
