# Generated by Django 6.0.2 on 2026-03-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_materia_concurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='concurso',
        ),
    ]
