# Generated by Django 6.0.2 on 2026-03-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_remove_materia_concurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciaFundamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=1.0)),
                ('fundamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='academico.fundamento')),
                ('prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueia', to='academico.fundamento')),
            ],
            options={
                'unique_together': {('fundamento', 'prerequisito')},
            },
        ),
    ]
