# Generated by Django 6.0.2 on 2026-03-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_dependenciafundamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='nivel_dinamico',
            field=models.FloatField(blank=True, default=1000, null=True),
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.concurso')),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='prova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='academico.prova'),
        ),
    ]
