# Generated by Django 6.0.2 on 2026-03-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_questao_numero_alter_questao_nivel_dinamico_prova_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamento',
            name='nivel_cognitivo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fundamento',
            name='tipo_cognitivo',
            field=models.CharField(default='conceito', max_length=50),
        ),
    ]
