# Generated by Django 6.0.2 on 2026-03-09 19:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_fundamento_nivel_cognitivo_fundamento_tipo_cognitivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamento',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True),
        ),
    ]
