# Generated by Django 6.0.2 on 2026-03-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_fundamento_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamento',
            name='embedding',
        ),
        migrations.CreateModel(
            name='FundamentoEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vetor', models.JSONField()),
                ('fundamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_vector', to='academico.fundamento')),
            ],
        ),
    ]
