# Generated by Django 6.0.2 on 2026-03-04 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoResolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertou', models.BooleanField()),
                ('tempo_em_segundos', models.PositiveIntegerField()),
                ('data_resolucao', models.DateTimeField(auto_now_add=True)),
                ('modo', models.CharField(choices=[('L', 'Lista'), ('S', 'Simulado')], max_length=1)),
                ('opcao_escolhida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.opcao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_limite', models.IntegerField()),
                ('pontuacao_final', models.FloatField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('concurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.concurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
